version: '0.0.1'

services:
  spring-boot-lab:
    container_name: spring-boot-lab
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://spring-boot-lab-db:5432/spring-boot-lab-database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  postgres:
    image: postgres:latest
    container_name: spring-boot-lab-db
    environment:
      POSTGRES_DB: spring-boot-lab-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"