name: Dynamic Application Security Testing

on:
  workflow_dispatch:

env:
  JAVA_VERSION: 21
  GRADLE_VERSION: 8.5

jobs:
  dast-scan:
    name: DAST Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'

      - name: Set up Gradle ${{ env.GRADLE_VERSION }}
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Set Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Build application
        run: ./gradlew build

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
      - name: Start Application Container
        run: docker compose up -d
    
      - name: Wait 30 seconds to start application
        run: sleep 30

      - name: Check container logs
        run: docker logs spring-boot-lab

      - name: Verify application status
        run: curl -s localhost:9090/com.amazingcode.in
     
      - name: Run ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:9090/com.amazingcode.in'
          cmd_options: '-a -j -l WARN -r report_html.html -w report_md.md -J report_json.json -z "-addoninstallall" '
          allow_issue_writing: true

      - name: Convert ZAP JSON to SARIF
        run: |
          jq -r '
          {
            "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
            "version": "2.1.0",
            "runs": [
              {
                "tool": {
                  "driver": {
                    "name": "OWASP ZAP",
                    "informationUri": "https://www.zaproxy.org/",
                    "version": ."@version",
                    "rules": [
                      .site[].alerts[] | {
                        "id": "ZAP-\(.pluginid)",
                        "shortDescription": {
                          "text": .name
                        },
                        "fullDescription": {
                          "text": .desc | gsub("</?p>"; " ")
                        },
                        "help": {
                          "text": (
                            "Solution: " + (.solution | gsub("</?p>"; " ")) +
                            " Reference: " + (.reference | gsub("</?p>"; " ")) +
                            if .otherinfo != "" then " Other info: " + (.otherinfo | gsub("</?p>"; " ")) else "" end
                          )
                        },
                        "defaultConfiguration": {
                          "level": (
                            if .riskcode == "3" then "error"
                            elif .riskcode == "2" then "warning"
                            elif .riskcode == "1" then "note"
                            else "none"
                            end
                          )
                        },
                        "properties": {
                          "tags": [
                            "security",
                            "CWE-\(.cweid)",
                            "WASC-\(.wascid)"
                          ],
                          "precision": (
                            if .confidence == "3" then "high"
                            elif .confidence == "2" then "medium"
                            else "low"
                            end
                          ),
                          "security-severity": .riskcode
                        }
                      }
                    ]
                  }
                },
                "results": [
                  .site[].alerts[] | .instances[] as $instance | {
                    "ruleId": "ZAP-\(.pluginid)",
                    "level": (
                      if .riskcode == "3" then "error"
                      elif .riskcode == "2" then "warning"
                      elif .riskcode == "1" then "note"
                      else "none"
                      end
                    ),
                    "message": {
                      "text": .desc | gsub("</?p>"; " ")
                    },
                    "locations": [
                      {
                        "physicalLocation": {
                          "artifactLocation": {
                            "uri": $instance.uri
                          }
                        }
                      }
                    ],
                    "properties": {
                      "issue_confidence": .confidence,
                      "issue_severity": .riskcode,
                      "risk_desc": .riskdesc,
                      "method": $instance.method,
                      "param": $instance.param,
                      "attack": $instance.attack,
                      "evidence": $instance.evidence,
                      "otherinfo": ($instance.otherinfo // ""),
                      "cwe_id": .cweid,
                      "wasc_id": .wascid
                    }
                  }
                ],
                "invocations": [
                  {
                    "executionSuccessful": true,
                    "timestamp": ."@generated"
                  }
                ]
              }
            ]
          }' report_json.json > zap_report.sarif

      # - name: Upload SARIF report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: DAST_Report.sarif
      #     path: ./zap_report.sarif

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: DAST_Report.html
          path: ./report_html.html

      - name: Verify directory contents
        run: ls -alh .

      - name: Package SARIF Report & Upload to Container registry
        run: |
          echo "FROM alpine" > Dockerfile
          echo "COPY zap_report.sarif /zap_report.sarif" >> Dockerfile
          echo "CMD [\"cat\", \"/zap_report.sarif\"]" >> Dockerfile

          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')

          IMAGE_TAG="ghcr.io/${REPO_OWNER}/${REPO_NAME}/dast-report:latest"

          docker build -t $IMAGE_TAG .
          docker push "$IMAGE_TAG"

          echo "Pull Image Using Command: docker pull $IMAGE_TAG"
          echo "Extract Report Using Command: docker run --rm $IMAGE_TAG > zap_report.sarif"

      - name: Cleanup containers
        if: always()
        run: |
          docker compose down
          docker image prune --force || true
          